# Generated by Django 2.2 on 2020-05-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20200504_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='是否可见', verbose_name='是否可见'),
        ),
    ]
