# Generated by Django 2.2 on 2020-02-25 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200221_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentuser',
            options={'verbose_name': '留言用户', 'verbose_name_plural': '留言用户'},
        ),
    ]
