# Generated by Django 2.2 on 2020-04-03 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20200403_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_type',
            new_name='type',
        ),
    ]
