# Generated by Django 2.2 on 2020-04-03 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0004_auto_20200403_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentreply',
            old_name='replay_to',
            new_name='author',
        ),
        migrations.AddField(
            model_name='commentreply',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reply_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
