# Generated by Django 2.2 on 2020-04-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_verifycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱'),
        ),
    ]
