# Generated by Django 2.2 on 2020-02-18 07:49

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('is_visible', models.BooleanField(default=False, help_text='是否可见', verbose_name='是否可见')),
            ],
            options={
                'verbose_name': '文章标签',
                'verbose_name_plural': '文章标签',
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('code', models.CharField(default='', help_text='类别code', max_length=30, verbose_name='类别code')),
                ('is_visible', models.BooleanField(default=False, help_text='是否可见', verbose_name='是否可见')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父类别', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='articles.ArticleCategory', verbose_name='父类别')),
            ],
            options={
                'verbose_name': '文章类别',
                'verbose_name_plural': '文章类别',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
                ('title', models.CharField(max_length=150, verbose_name='文章标题')),
                ('summary', models.TextField(default='', max_length=300, verbose_name='文章摘要')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='文章内容')),
                ('click_num', models.IntegerField(default=0, verbose_name='浏览量')),
                ('fav_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.ArticleCategory', verbose_name='文章类别')),
                ('tags', models.ManyToManyField(to='articles.ArticleTag', verbose_name='文章标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
