# Generated by Django 2.2 on 2020-03-11 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200221_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecategory',
            name='category_type',
        ),
        migrations.RemoveField(
            model_name='articlecategory',
            name='parent_category',
        ),
    ]
