# Generated by Django 2.2 on 2020-05-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200314_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(default='', max_length=300, verbose_name='文章摘要'),
        ),
    ]
